version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: tks23/nodejs-nginx-ocp-demo
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network
  webserver:
    image: nginx:mainline-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./nginx-conf:/etc/nginx/conf.d
    depends_on:
      - nodejs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
