version: "3"

services:
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: tks23/nodejs-nginx-ocp-demo
    container_name: nodejs
    restart: unless-stopped
    networks:
      - app-network
  webserver:
    image: tks23/nginx-unprivileged:stable
    container_name: webserver
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - nodejs
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
