apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs
  name: nodejs
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: tks23/nodejs-nginx-ocp-demo
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
