# Needed to crete myself, Kompose did not create this for me
apiVersion: v1
kind: Service
metadata:
  labels:
    io.kompose.service: nodejs
  name: nodejs
  namespace: nodejs-nginx-ocp-demo
spec:
  clusterIP: 172.30.140.7
  ports:
    - name: "3000"
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    io.kompose.service: rnodejs
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
