apiVersion: v1
kind: ImageStream
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: webserver
  name: webserver
spec:
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: nginxinc/nginx-unprivileged
    generation: null
    importPolicy: {}
    name: latest
status:
  dockerImageRepository: ""
